package com.p1_7.game.logic;

import com.p1_7.game.dungeon.Room;
import com.p1_7.game.question.DecoyGenerator;
import com.p1_7.game.question.Question;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * stateless service that assigns answer labels to dungeon rooms for one floor.
 *
 * the first room in the input list is always treated as the spawn; it receives
 * no label. the remaining rooms are shuffled and a subset receives labels drawn
 * from the question's correct answer and generated decoys.
 */
public class RoomLabeller {

    /** shared decoy generator; DecoyGenerator is stateless so one instance suffices */
    private static final DecoyGenerator DECOY_GENERATOR = new DecoyGenerator();

    /**
     * labels a set of rooms for one dungeon floor given a question and rng.
     *
     * rooms.get(0) is wrapped as the unlabelled spawn room. the remaining rooms
     * are shuffled; min(answerRoomCount, remaining) of them receive labels —
     * exactly one carrying the correct answer and the rest carrying decoys from
     * DecoyGenerator. labelled rooms are shuffled so the correct answer does not
     * always appear in the same position. unlabelled non-spawn rooms are appended
     * at the end.
     *
     * @param rooms           the full list of rooms; must not be null; must have at least 2 elements
     * @param question        the question whose answer is used for labelling; must not be null
     * @param answerRoomCount the desired number of rooms to label (clamped to remaining.size()); when
     *                        labelCount - 1 exceeds 3, decoy values cycle and may repeat across rooms
     * @param rng             random number generator; must not be null
     * @return a list starting with the spawn room followed by labelled and unlabelled rooms
     * @throws IllegalArgumentException if rooms or question or rng is null, or if rooms has fewer than 2 elements
     */
    public List<LabelledRoom> label(List<Room> rooms, Question question, int answerRoomCount, Random rng) {
        if (rooms == null) {
            throw new IllegalArgumentException("rooms must not be null");
        }
        if (question == null) {
            throw new IllegalArgumentException("question must not be null");
        }
        if (rng == null) {
            throw new IllegalArgumentException("rng must not be null");
        }
        if (rooms.size() < 2) {
            throw new IllegalArgumentException("rooms must contain at least 2 elements");
        }
        if (rooms.contains(null)) {
            throw new IllegalArgumentException("rooms must not contain null elements");
        }

        // rooms.get(0) is always the spawn — it gets no label
        LabelledRoom spawnRoom = new LabelledRoom(rooms.get(0), null);

        // shuffle a mutable copy of the non-spawn rooms
        List<Room> nonSpawnRooms = new ArrayList<>(rooms.subList(1, rooms.size()));
        Collections.shuffle(nonSpawnRooms, rng);

        // clamp to the number of rooms actually available
        int labelCount = Math.min(answerRoomCount, nonSpawnRooms.size());

        // build labels: one correct, rest are decoys
        List<LabelledRoom> labelledRooms = buildLabelledRooms(nonSpawnRooms, question, labelCount, rng);

        // shuffle so correct answer is not predictably positioned
        Collections.shuffle(labelledRooms, rng);

        // wrap remaining non-selected rooms without a label
        List<LabelledRoom> unlabelledRooms = new ArrayList<>();
        for (int i = labelCount; i < nonSpawnRooms.size(); i++) {
            unlabelledRooms.add(new LabelledRoom(nonSpawnRooms.get(i), null));
        }

        // assemble final list: spawn first, then labelled, then unlabelled
        List<LabelledRoom> result = new ArrayList<>();
        result.add(spawnRoom);
        result.addAll(labelledRooms);
        result.addAll(unlabelledRooms);

        return Collections.unmodifiableList(result);
    }

    /**
     * builds labelled rooms for the first labelCount entries in nonSpawnRooms.
     *
     * the first room receives a label with the correct answer; the remaining
     * rooms receive decoy labels generated by DecoyGenerator.
     *
     * @param nonSpawnRooms the shuffled list of non-spawn rooms
     * @param question      the question providing the correct answer and operator/operands
     * @param labelCount    the number of rooms to label
     * @param rng           random number generator for the decoy generator
     * @return a mutable list of labelled rooms of size labelCount
     */
    private List<LabelledRoom> buildLabelledRooms(List<Room> nonSpawnRooms, Question question, int labelCount, Random rng) {
        if (labelCount == 0) {
            return new ArrayList<>();
        }

        int correctAnswer = question.getCorrectAnswer();

        // generate the required number of decoys (labelCount - 1)
        List<Integer> decoys = DECOY_GENERATOR.generate(
            correctAnswer,
            question.getOperator(),
            question.getOperands(),
            rng
        );

        List<LabelledRoom> labelled = new ArrayList<>();

        // first room gets the correct answer label
        labelled.add(new LabelledRoom(nonSpawnRooms.get(0), new RoomLabel(correctAnswer, true)));

        // remaining rooms get decoy labels
        for (int i = 1; i < labelCount; i++) {
            // cycle through decoys if labelCount - 1 > decoys.size()
            int decoyValue = decoys.get((i - 1) % decoys.size());
            labelled.add(new LabelledRoom(nonSpawnRooms.get(i), new RoomLabel(decoyValue, false)));
        }

        return labelled;
    }
}
